blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/rramoscabral/PL-7008---Training---Create-agents-in-Microsoft-Copilot-Studio/discussions
    about: Ask questions and discuss with other community members